### ISSUE TITLE
how should I do to test my own image with the model？

### ISSUE THREAD

**Issue by liyulin9541** [tgeorgy/mgan#7]

**Comment by tgeorgy** [comment]
Hi, unfortunately I have abandoned this project since I am too much occupied on work. To run inference you would need to:
1. Figure out how images are cropped and scaled in CelebA dataset and implement preprocessing by yourself.
2. Write inference code to feed image into the model and get results.

I didn't try to run it on other images, so there's a chance it won't work e.g. if the distribution differs too much.

Also, I am wondering, what are you trying to do with it? There might be other implementations that suit better.
